name: Java CI with Maven production

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Maven Package
      run: mvn -B clean package --file pom.xml -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: [ build_and_test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: maven
      - run: mvn -B package --file pom.xml -DskipTests
      - run: mkdir staging && cp target/customer-account-0.0.1-SNAPSHOT.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build_and_test ]

    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Container image
        run: docker build -t ${{ secrets.DOCKER_REPO }}:latest .
      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}
